# Generated by Django 5.0.4 on 2025-03-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselmodel',
            name='Titile',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='placementmodel',
            name='Company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='placementmodel',
            name='Placedon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementmodel',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to='Placement profile'),
        ),
    ]
